name: Publish Docker image
on:
  push:
    branches:
      - main
jobs:
  build_test_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: DATE_STRING=`date +%Y_%m_%d_%H:%M`
      - run: IMAGE_NAME="$GITHUB_REPOSITORY_$DATE_STRING:test_build"
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-no-buildkit || true
      - run: docker build . -t $IMAGE_NAME --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/$GITHUB_REPOSITORY
      - run: docker tag $IMAGE_NAME docker.pkg.github.com/$GITHUB_REPOSITORY/$GITHUB_REPOSITORY && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$GITHUB_REPOSITORY || true