name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:
  build_test_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: docker pull docker.pkg.github.com/tal-leibman/messages-app-flask || true
      - run: docker build . -t ${GITHUB_SHA:0:9} --cache-from=docker.pkg.github.com/tal-leibman/messages-app-flask:latest
      - run: docker tag latest docker.pkg.github.com/tal-leibman/messages-app-flask && docker push docker.pkg.github.com/tal-leibman/messages-app-flask || true