name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:
  build_test_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: docker pull docker.pkg.github.com/tal-leibman/messages-app-flask/messages-app-flask-image || true
#      - run: docker build . -t ${GITHUB_SHA:0:9} --cache-from=docker.pkg.github.com/tal-leibman/messages-app-flask/messages-app-flask-image
      - run: docker build . -t ${GITHUB_SHA:0:9}
      - run: docker push docker.pkg.github.com/tal-leibman/messages-app-flask/messages-app-flask-image:${GITHUB_SHA:0:9}:latest
#      - run: docker tag latest docker.pkg.github.com/tal-leibman/messages-app-flask/messages-app-flask-image:${GITHUB_SHA:0:9} && docker push docker.pkg.github.com/tal-leibman/messages-app-flask/messages-app-flask-image:${GITHUB_SHA:0:9} || true